version: "3.3"

services:
   deploy:
      container_name: qa_ser
      image: shaikghouse/muni
      tty: true
      volumes:
         - "/home/workspace/dev-data:/home/workspace/dev-data/"
      ports:
         - "8021:8080"
      networks: 
         - net

   deploy:
      container_name: uat_ser
      image: shaikghouse/muni
      tty: true
      volumes:
         - "/home/workspace/dev-data:/home/workspace/dev-data/"
      ports: 
         - "8022:8080"
      networks:
         - net

   deploy:
      container_name: prod
      image: shaikghouse/muni
      tty: true
      volumes:
         - "/home/workspace/dev-data:/home/workspace/dev-data/"
      ports: 
         - "8023:8080"
      networks:
         - net

volumes: 
   cont_data:


networks:
   net:
